src/TakagiSugeno/Controllers/InputsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TakagiSugeno.Tools;
using TakagiSugeno.Model.ViewModels;
using TakagiSugeno.Model.Services;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace TakagiSugeno.Controllers
{
    public class InputsController : Controller
    {
        private InputsService _inputsService;
        private VariablesService _variablesService;
        public InputsController(InputsService inputsService, VariablesService variablesService)
        {
            _inputsService = inputsService;
            _variablesService = variablesService;
        }

        public IActionResult Details(int? id)
        {
            InputVM vm = new InputVM();
            if (id.HasValue)
            {
                vm = _inputsService.GetInput(id.Value);
            }
            ViewBag.SystemId = vm.SystemId;
            if (Request.IsAjaxRequest())
                return PartialView(vm);
            
            return View(vm);
        }

        public IActionResult SystemInputs(int systemId)
        {
            int inputId = _inputsService.FirstSystemInput(systemId);
            if(inputId != -1)
                return RedirectToAction("Details", new { id = inputId});
            else
                return RedirectToAction("Add", new { systemId = systemId });
        }

        public IActionResult AddVariable(int fakeId)
        {
            VariableVM variable = _variablesService.CreateVariable(fakeId, Model.IOType.Input);
            return PartialView("VariableRow", variable);
        }

        public IActionResult ChangeVariableType(VariableVM variable)
        {
            _variablesService.ChangeVariableType(variable);
            return PartialView("VariableRow", variable);
        }

        public IActionResult RemoveVariable(InputVM viewModel, int variableId)
        {
            _variablesService.RemoveVariable(viewModel, variableId);
            return PartialView("Details", viewModel);
        }

        [HttpPost]
        public IActionResult Save([FromBody] InputVM viewModel)
        {
            SaveResult res = _inputsService.Save(viewModel);
            return Json(res);
        }
        [HttpPost]
        public IActionResult Remove(int id)
        {
            _inputsService.Remove(id);
            return Json(string.Empty);
        }

        public IActionResult InputsList(int systemId)
        {
            return PartialView("List", _inputsService.GetSystemInputs(systemId));
        }

        public IActionResult Add(int systemId)
        {
            ViewBag.IsNewInput = true;
            InputVM vm = _inputsService.AddInput(systemId);
            ViewBag.SystemId = vm.SystemId;
            if (Request.IsAjaxRequest())
                return PartialView("Details", vm);          
            return View("Details", vm);
        }

    }
}

src/TakagiSugeno/Controllers/OutputsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TakagiSugeno.Model.Services;
using TakagiSugeno.Model.ViewModels;
using TakagiSugeno.Tools;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace TakagiSugeno.Controllers
{
    public class OutputsController : Controller
    {

        private OutputsService _outputsService;
        private VariablesService _variablesService;
        public OutputsController(OutputsService outputsService, VariablesService variablesService)
        {
            _outputsService = outputsService;
            _variablesService = variablesService;
        }

        public IActionResult OutputsList(int systemId)
        {
            return PartialView("List", _outputsService.GetSystemOutputs(systemId));
        }

        public IActionResult Details(int? id)
        {
            OutputVM vm = new OutputVM() { Variables = new List<VariableVM>(), OutputId = -1 };
            if (id.HasValue && id.Value != -1)
            {
                vm = _outputsService.GetOutput(id.Value);
            }
            ViewBag.SystemId = vm.SystemId;
            if (Request.IsAjaxRequest())
                return PartialView("OutputDetails", vm);
            
            return View("OutputDetails", vm);
        }

        public IActionResult SystemOutputs(int systemId)
        {
            int outputId = _outputsService.FirstSystemOutput(systemId);
            if (outputId != -1)
                return RedirectToAction("Details", new { id = outputId });
            else
                return RedirectToAction("Add", new { systemId = systemId });
        }

        public IActionResult AddVariable(int fakeId)
        {
            VariableVM variable = _variablesService.CreateVariable(fakeId, Model.IOType.Output);
            return PartialView("~/Views/Inputs/VariableRow.cshtml", variable);
        }

        [HttpPost]
        public IActionResult ChangeVariableType(VariableVM variable, int? systemId)
        {
            if (systemId.HasValue)
            {
                _variablesService.ChangeVariableType(variable, systemId.Value);
            }
            return PartialView("~/Views/Inputs/VariableRow.cshtml", variable);
        }

        [HttpPost]
        public IActionResult Save([FromBody] OutputVM viewModel)
        {
            SaveResult res = _outputsService.Save(viewModel);
            return Json(res);
        }

        public IActionResult Remove(int id)
        {
            _outputsService.Remove(id);
            return Json(string.Empty);
        }

        public IActionResult Add(int systemId)
        {
            ViewBag.IsNewOutput = true;
            OutputVM vm = _outputsService.AddOutput(systemId);
            ViewBag.SystemId = vm.SystemId;
            if (Request.IsAjaxRequest())
                return PartialView("OutputDetails", vm);       
            return View("OutputDetails", vm);
        }

    }
}

src/TakagiSugeno/Controllers/RulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TakagiSugeno.Model.ViewModels;
using TakagiSugeno.Model.Services;
using TakagiSugeno.Tools;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace TakagiSugeno.Controllers
{
    public class RulesController : Controller
    {
        private RulesService _service;

        public RulesController(RulesService service)
        {
            _service = service;
        }

        public IActionResult SystemRules(int systemId)
        {
            RuleGeneralVM vm = _service.GetSystemRules(systemId);
            ViewBag.SystemId = systemId;
            if (Request.IsAjaxRequest())
                return PartialView(vm);
            ViewBag.SystemId = systemId;
            return View(vm);
        }

        public IActionResult NewRule(int systemId, int ruleId)
        {
            return PartialView("RuleRow", _service.CreateNewRule(systemId, ruleId));
        }

        [HttpPost]
        public IActionResult Save([FromBody] List<RuleVM> rules)
        {
            _service.Save(rules);
            return Json("");
        }

        [HttpPost]
        public IActionResult ClearRules(int systemId)
        {
            _service.ClearRules(systemId);
            return Json("");
        }
    }
}

src/TakagiSugeno/Controllers/SystemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TakagiSugeno.Model.Services;
using TakagiSugeno.Model.ViewModels;
using System.Text;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace TakagiSugeno.Controllers
{
    public class SystemsController : Controller
    {
        private SystemsService _service;
        private SystemStateHelper _stateHelper;

        public SystemsController(SystemsService service, SystemStateHelper stateHelper)
        {
            _service = service;
            _stateHelper = stateHelper;
        }
        // GET: /<controller>/
        public IActionResult SystemsList(int? openedSystem)
        {
            ViewBag.SystemId = openedSystem;
            return View(_service.GetSystems());
        }

        public IActionResult New()
        {
            int newId = _service.CreateSystem();
            return RedirectToAction("Index", "SystemOverview", new { systemId = newId });
        }

        public IActionResult Publish([FromBody] PublishVM publishData)
        {
            _service.Publish(publishData);
            return Json("");
        }

        public IActionResult Clone(int systemId)
        {
            int newId = _service.CloneSystem(systemId);
            return RedirectToAction("Index", "SystemOverview", new { systemId = newId });
        }
        [HttpPost]
        public IActionResult IsSystemPublished(int systemId)
        {
            return Json(_stateHelper.IsSystemPublished(systemId));
        }

        public IActionResult SaveToFile(int systemId)
        {
            string systemJson = _service.SystemToJson(systemId);
            return File(Encoding.UTF8.GetBytes(systemJson),
                "application/json", "TakagiSugenoSystem.json");
        }

        [HttpPost]
        public IActionResult ReadFromFile()
        {
            var file = Request.Form.Files.GetFile("system");
            int? res = _service.ReadFromFile(file);
            return Json(res);
        }
    }
}

src/TakagiSugeno/Views/Shared/SystemMenu.cshtml
@model int
@inject TakagiSugeno.Model.Services.SystemStateHelper _stateHelper;
@{

    var inputsCount = _stateHelper.GetInputsCount(Model);
    var outputsCount = _stateHelper.GetOutputsCount(Model);
    var rulesCount = _stateHelper.GetRulesCount(Model);
}

<li class="dropdown system-menu">
    <a asp-area="" asp-controller="SystemOverview" asp-action="Index" asp-route-systemId="@Model" id="SysId" data-system-id="@Model">Wybrany System <span class="caret"></span></a>
    <ul class="dropdown-menu">
        <li><a asp-area="" asp-controller="Inputs" asp-action="SystemInputs" asp-route-systemId="@Model">Wejścia</a></li>
        <li><a asp-area="" asp-controller="Outputs" asp-action="SystemOutputs" asp-route-systemId="@Model">Wyjścia</a></li>
        @if (inputsCount == 0 || outputsCount == 0)
        {
            <li id="rulesLink" class="disabled"><a asp-area="" asp-controller="Rules" asp-action="SystemRules" asp-route-systemId="@Model">Reguły</a></li>
        }
        else
        {
            <li id="rulesLink"><a asp-area="" asp-controller="Rules" asp-action="SystemRules" asp-route-systemId="@Model">Reguły</a></li>
        }
        @if (inputsCount == 0 || outputsCount == 0 || rulesCount == 0)
        {
            <li id="calcLink" class="disabled"><a asp-area="" asp-controller="OutputCalc" asp-action="Index" asp-route-systemId="@Model">Wyznaczanie wyjść</a></li>
        }
        else
        {
            <li id="calcLink"><a asp-area="" asp-controller="OutputCalc" asp-action="Index" asp-route-systemId="@Model">Wyznaczanie wyjść</a></li>
        }
        
    </ul>
</li>

src/TakagiSugeno/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TakagiSugeno</title>

    <environment names="Development">
        <!--<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />-->
        <link rel="stylesheet" type="text/css" href="~/lib/datatables/datatables.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/scrollbars/jquery.mCustomScrollbar.min.css" />
        
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/jquery.canvasjs.min.js"></script>
        <script src="~/scrollbars/jquery.mCustomScrollbar.concat.min.js"></script>
        
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" type="text/css" href="~/lib/datatables/datatables.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/scrollbars/jquery.mCustomScrollbar.min.css" />

        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/jquery.canvasjs.min.js"></script>
        <script src="~/scrollbars/jquery.mCustomScrollbar.concat.min.js"></script>

        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="#" class="navbar-brand">TakagiSugeno</a>
            </div>
            <div class="navbar-collapse collapse">
                
                <ul class="nav navbar-nav">   
                    <li><a asp-area="" asp-controller="Systems" asp-action="SystemsList" asp-route-openedSystem="@ViewBag.SystemId">Przeglądaj </a></li>
                    <li><a asp-area="" asp-controller="Systems" asp-action="New">Nowy </a></li>
                    @if(ViewBag.SystemId != null)
                    {
                        Html.RenderPartial("SystemMenu", (int)ViewBag.SystemId);
                    }  
                </ul>
            </div>
        </div>
    </div>
    @if (ViewBag.Title == "Wejścia")
    {
        @inject TakagiSugeno.Model.Services.InputsService InputService
        <div class="navbar navbar-inverse navbar-fixed-left">
            <div class="nav-header row">
                <div class="col-sm-10"><h3>Wejścia</h3></div>
                <div class="col-sm-2"><button class="btn btn-success pull-right btn-add" id="addInput" onclick="addInput()"><span class="glyphicon glyphicon-plus" ></span></button></div>
            </div>
            <div class="menu-io-list">
            @{Html.RenderPartial("~/Views/Inputs/List.cshtml", InputService.GetSystemInputs((int)ViewBag.SystemId));}
            </div>
        <br /><br />
        </div>

    } 
    else if (ViewBag.Title == "Wyjścia")
    {
        @inject TakagiSugeno.Model.Services.OutputsService OutputService
        <div class="navbar navbar-inverse navbar-fixed-left ">
            <div class="nav-header row">
                <div class="col-sm-10"><h3>Wyjścia</h3></div>
                <div class="col-sm-2"><button class="btn btn-success pull-right btn-add" id="addOutput" onclick="addOutput()"><span class="glyphicon glyphicon-plus"></span></button></div>
            </div>
            <div class="menu-io-list">
                @{Html.RenderPartial("~/Views/Outputs/List.cshtml", OutputService.GetSystemOutputs((int)ViewBag.SystemId));}
            </div>
            <br /><br />
            </div>
    }
    <div class="container body-content">
        @RenderBody()
    </div>

    <environment names="Development">
        <!--<script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/jquery.canvasjs.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>-->
    </environment>
    <environment names="Staging,Production">
        <!--<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>-->
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>